---
title: "How to Extract Korean Patents from KIPRIS: By the Applicant Name"
subtitle: "Multiple applicants, Multiple pages" 
author: "Sehee Park" 
date: "`r Sys.date()`" 
output: github_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Load packages 
```{r}
library(tidyverse)
library(httr) 
library(xml2) 
```

## Prepare data
```{r}
# URL for KIPRIS Plus REST
url <- "http://plus.kipris.or.kr/kipo-api/kipi/patUtiModInfoSearchSevice/getAdvancedSearch"

# Personal key to access the REST api 
mykey <- "use your access key"

# Load your applicant data: make sure it is a vector 
applicants <- "use your data"
# Use this sample data if you want to experiment. 
# applicants <- readRDS("./sample_data/sample_applicant.rds") %>% as_vector() 
```

## Get Patents according to your query
```{r get-patent-function} 
# Define a function: 
# Variables multi applicants (x), multi pages (i)

get_patents <- function(x) {
  # Set variables for each applicant 
  applicant_name <- applicants[x] 
  cumul_df <- tibble() 
  i <- 1
  # repeated patent extracts if there is more than one page (500 patents) 
  repeat {
    temp <- httr::GET(url, query = list(applicant = applicant_name, 
                                        # Set your preferred dates here. Keep the forma. 
                                        applicationDate = "20130101~20191231",
                                        # Extract patents: TRUE 
                                        patent = TRUE, 
                                        # Do not extract utilities: FALSE 
                                        utility = FALSE, 
                                        # The final dataset does not distinguish patents from utilites. 
                                        # Hence I prefer to extract them in separate dataframes. 
                                        # Set the maximun number of patents per applicant. 
                                        numOfRows = 500, # default == 20 
                                        # multi pages
                                        pageNo = i, # default == 1
                                        # I() "as is" is required to retain its original format. 
                                        ServiceKey = I(mykey)))
    
    # Extract xml information 
    temp_node <- temp %>% 
      read_xml() %>% 
      xml_find_all(xpath = "//item")  
    
    # Bind data into one tibble format, only when there are one or more patents. 
    if (length(temp_node) == 0) {
      # Unmark if you want to check the loop status 
      # print(paste0("applicant: ", applicant_name))
      # print(paste0("page: ", i))
      # print(paste0("no_patents: ", length(temp_node)))
      break
    } else {
      temp_df <- map_dfr(seq_along(temp_node), function(y) {
        temp_row <- xml_find_all(temp_node[y], './*')
        tibble(
          name = applicant_name, 
          page = i, 
          idx = y,
          key = temp_row %>% xml_name(), 
          value = temp_row %>% xml_text()
          )
        }
      ) %>% spread(key, value) 
      
      # Unmark if you want to check the loop status 
      # print(paste0("applicant: ", applicant_name))
      # print(paste0("page: ", i))
      # print(paste0("no_patents: ", nrow(temp_df)))
      
      # Increase page number 
      i <- i + 1
      
      # Give 0.1 sec interval between each applicant query: KIPRIS limits 50 inputs per sec. 
      Sys.sleep(0.1)
    }
    
    # Cumulated patents dataframe per applicant
    cumul_df <- rbind(cumul_df, temp_df)
    # cumul_df <- bind_rows(cumul_df, temp_df) : bind_rows() does not work here. 
    
    # Unmark if you want to check the loop status of cumul_df 
    # print(paste0("cumul patents: ", nrow(cumul_df)))
    
    if (length(temp_node) < 500) {
      break
    }
  } 
  return (cumul_df)
} 
```

## Get real patent data from own applicants 
```{r df-patent}
df_patents <- map_dfr(seq_along(applicants), get_patents)
```

## Notice 
If you want to use the KIPRIS OpenApi service for a business, you may apply for a paid account. 
